FROM node as build-deps

WORKDIR /usr/src/app

# installing dependencies
COPY webapp/package.json webapp/yarn.lock ./
RUN yarn

# building react app
COPY ./webapp ./
RUN yarn build

FROM nginx:stable-alpine AS runner
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
COPY scripts/nginx.conf /etc/nginx/nginx.conf
COPY scripts/run-server /

# Frontend settings
ENV API_HOST "localhost:5000"

EXPOSE 80

CMD ["/run-server"]
